export const All_Projects = [
    {
        src: '/Solar-3D.png',
        title: '3D Solar System',
        description: 'This 3D-Solar System know about our solar system',
        technologies: 'Technologies: HTML | CSS | JavaScript',
        view: 'https://solar-system-3-d.vercel.app/',
        href: 'https://github.com/Sumit262601/Solar-System-3D',
    },
    {
        src: '/SpaceWebsite.png',
        title: 'Space Portfolio',
        description: 'This is my portfolio to introduce my Skills and Expertise',
        technologies: 'Technologies: Next Js | TypeScript | Tailwind | Framer Motion',
        href: 'https://github.com/Sumit262601/Space-Potfolio',
        view: 'https://github.com/Sumit262601/Space-Potfolio',
    },
    {
        src: '/Chatter.png',
        title: 'Chatter',
        description: "Here, Is a Chatter Application like a What'sApp",
        technologies: 'Technologies: React Native | Tailwind | Firebase | Redux',
        href: 'https://github.com/Sumit262601/Chatter',
        view: '',
    },
    {
        src: '/Login-UI.png',
        title: 'Login UI',
        description: 'This UX/UI Login design to apply in your project',
        technologies: 'Technologies: React Native | Tailwind | Postcss',
        href: 'https://github.com/Sumit262601/Login-UI',
        view: '',
    },
    {
        src: '/TextUtilies.png',
        title: 'TextUtilies',
        description: 'There is text converter in lower, upper, clipboard',
        technologies: 'Technologies: HTML | CSS | JavaScript',
        href: 'https://github.com/Sumit262601/TextUtilies',
        view: 'https://text-utilies.vercel.app/',
    },
    {
        src: '/Disney.png',
        title: 'Disney Clone',
        description: 'This Disney-Clone project to practice React and the I should use MovieDatabase Api to fetch this content in latest views',
        technologies: 'Technologies: React Js | Bootstrap-5 | MovieDB Api',
        href: 'https://github.com/Sumit262601/Disney-Clone',
        view: 'https://disneyy-clone.vercel.app/',
    },
] 